### ISSUE TITLE
Checar erro  na atualização do BD de ocorrências

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#56]
Conforme conversamos no Telegram:

```
error: Uncaught Error: read ECONNRESET 
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9) 
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:139:10) 
    at TCP.onStreamRead [as onread] (ext:deno_node/internal/stream_base_commons.ts:209:20) 
    at TCP.[#read](tg://search_hashtag?hashtag=read) (ext:deno_node/internal_binding/stream_wrap.ts:244:12) 
    at eventLoopTick (ext:core/01_core.js:181:11) 
Error: Process completed with exit code 1.
```

**Comment by Phenome** [comment]
Pareceu ser um problema de memória nos Github-hosted runners.

Resolvido migrando pra um runner self-hosted, cuminando nesse commit: f5433a0ee963efc0fad880126fdbbf4371d5ed8d
